apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    function: app
spec:
  containers:
  - name: django-container
    image: ghcr.io/mdella/cis-92-sp26:milestone-5.2
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: django-config
    - secretRef:
        name: django-secret
    resources:
      requests:
        cpu: 1000m 
        memory: 1024Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 1000m 
        memory: 1024Mi
        ephemeral-storage: 10Mi