apiVersion: v1
kind: Secret 
metadata:
  name: django-secret
stringData:
  SECRET_KEY_BAD: "this-is-a-bad-key"
data:
  SECRET_KEY: dGhpcy1pcy1hLWdvb2Qta2V5
  DJANGO_SUPERUSER_USERNAME: dGVzdGluZw==
  DJANGO_SUPERUSER_EMAIL: dGVzdGluZ0B0ZXN0aW5nLmNvbQ==
  DJANGO_SUPERUSER_PASSWORD: dGVzdGluZw==
stringData:
  POSTGRES_PASSWORD: "this-is-a-bad-password"
  POSTGRES_USER: "mysiteuser"